// src/utils/saveVideoAndCaption.ts
//
// Ported from the original expo-snippets/saveVideoAndCaption.js into
// this real project (TypeScript, actually installed dependencies).
// Ties together the video generated by the backend (lib/generateVideo.js
// + POST /api/generate-video) with the phone's gallery/clipboard/share sheet.

import * as MediaLibrary from 'expo-media-library';
import * as Clipboard from 'expo-clipboard';
import * as Sharing from 'expo-sharing';

export type SaveVideoResult = {
  videoSaved: boolean;
  captionCopied: boolean;
  permissionDenied: boolean;
  errorMessage: string | null;
};

/**
 * Saves a video to the phone's gallery and copies a caption to the
 * clipboard. Each step succeeds/fails independently, so the UI can show
 * accurate feedback even if only one of the two worked.
 *
 * @param videoUri - LOCAL file URI (download the video from the backend's
 *   remote URL first — see ListingReviewScreen's handleGenerateVideo for
 *   the download step via expo-file-system).
 * @param captionText - text to copy to the clipboard.
 */
export async function saveVideoAndCaption(videoUri: string, captionText: string): Promise<SaveVideoResult> {
  const result: SaveVideoResult = {
    videoSaved: false,
    captionCopied: false,
    permissionDenied: false,
    errorMessage: null,
  };

  // ---- Step 1: save video to gallery ----
  try {
    const { status } = await MediaLibrary.requestPermissionsAsync();
    if (status !== 'granted') {
      result.permissionDenied = true;
    } else {
      await MediaLibrary.saveToLibraryAsync(videoUri);
      result.videoSaved = true;
    }
  } catch (err: any) {
    result.errorMessage = `Video save failed: ${err.message}`;
  }

  // ---- Step 2: copy caption to clipboard ----
  try {
    if (captionText) {
      await Clipboard.setStringAsync(captionText);
      result.captionCopied = true;
    }
  } catch (err: any) {
    result.errorMessage = result.errorMessage
      ? `${result.errorMessage}; Caption copy failed: ${err.message}`
      : `Caption copy failed: ${err.message}`;
  }

  return result;
}

/** Opens the native share sheet with the video attached — works whether or not the gallery save succeeded. */
export async function shareVideoNow(videoUri: string): Promise<void> {
  const isAvailable = await Sharing.isAvailableAsync();
  if (!isAvailable) throw new Error('Sharing is not available on this device.');
  await Sharing.shareAsync(videoUri);
}
